### ISSUE TITLE
Conflicting text description and implementation on LinearElasticity

### ISSUE THREAD

**Issue by simo-11** [newfrac/fenicsx-fracture#5]
In picture and text it is said that second boundary condition is to block the horizontal component  on the right boundary.
In implementation second boundary condition is applied on top and is resulting picture shows that on right boundary there is horizontal displacement.

**Comment by simo-11** [comment]
Correct implementation is available at https://github.com/newfrac/fenicsx-fracture/blob/main/notebooks/utils/elastic_solver.py

**Comment by cmaurini** [comment]
Thanks a lot for reporting. I think it is fixed now.

**Comment by simo-11** [comment]
Pages give now 404 (not found). Possible pages are regenerated right now but this should be checked at some time.
https://newfrac.github.io/fenicsx-fracture/notebooks/linear-elasticity/00-Mesh.html
https://newfrac.github.io/fenicsx-fracture/notebooks/linear-elasticity/01-LinearElasticity.html

**Comment by cmaurini** [comment]
... due to `pyvista` which is extremely fragile and different in linux and macosx... It is tested, just I should have done a merge request.

Any contribution will be appreciated. Do not hesitate to propose merge request for fixing issues or improve the examples. 

Best,

Corrado
